#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct. 

case $SOURCE_BRANCH in
  staging*) WINEPKG=winehq-staging;;
  devel*) WINEPKG=winehq-devel;;
  *) WINEPKG=winehq-stable;;
esac

docker build --build-arg VCS_REF="`git rev-parse --short HEAD`" \
             --build-arg BUILD_DATE="`date -u +"%Y-%m-%dT%H:%M:%SZ"`" \
             --build-arg WINEPKG="$WINEPKG" \
             -t $IMAGE_NAME .
