---
name: Build Docker images
on:
  workflow_call:
    inputs:
      push:
        required: false
        type: boolean
    secrets:
      DOCKERHUB_TOKEN:
        required: false

permissions:
  contents: read

jobs:
  prepare:
    name: Build (and push) Docker image
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: tobix
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ inputs.push }}

      - name: Detect image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: tobix/wine

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build stable
        uses: docker/build-push-action@v6
        with:
          push: ${{ inputs.push }}
          tags: tobix/wine:stable
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            WINE_FLAVOUR=stable
          cache-to: type=local,dest=/tmp/buildx-cache,mode=max

      - name: Build devel
        uses: docker/build-push-action@v6
        with:
          push: ${{ inputs.push }}
          tags: tobix/wine:devel
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            WINE_FLAVOUR=devel
          cache-from: type=local,src=/tmp/buildx-cache

      - name: Build staging
        uses: docker/build-push-action@v6
        with:
          push: ${{ inputs.push }}
          tags: tobix/wine:staging
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            WINE_FLAVOUR=staging
          cache-from: type=local,src=/tmp/buildx-cache
