---
name: Lint Dockerfile
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: Lint Dockerfile
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Lint
        uses: hadolint/hadolint-action@v3.3.0
        with:
          failure-threshold: error
